# Generated by Django 4.2.3 on 2024-07-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='Username', max_length=50)),
                ('email', models.EmailField(default='Emaail', max_length=254)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
